### ISSUE TITLE
animated wallpaper?

### ISSUE THREAD

**Issue by siduck** [HTsuyoshi/my-dwm#1]
Hi @HTsuyoshi nice rice! how did you get the animated wallpaper?

**Comment by HTsuyoshi** [comment]
> Hi @HTsuyoshi nice rice! how did you get the animated wallpaper? 

Holy shit you I love your rices man.
I used `xwinwrap` my config is in a page on tldr or in my dotfiles/basic/script/animated_wallpaper.sh
;)
